baseURL = "https://www.blonohouses.com/"
enableRobotsTXT = true
languageCode = "en-us"
summarylength = 20
[[menu.main]]
name = "Home Value Request"
parent = "Buyers & Sellers"
url = "https://blonohouses.com/home-value-request"
weight = 3
[[menu.main]]
name = "Mortgage Calculator"
parent = "Buyers & Sellers"
url = "https://blonohouses.idxhome.com/mortcalc/137224"
weight = 2
[[menu.main]]
name = "Advanced Search"
parent = "Property Search"
url = "http://blonohouses.idxhome.com/listing/search/advanced/137224/34?location=Enter+cities%2C+zip+codes+or+neighborhoods&propertyType=SFR%2CCND&minListPrice=&maxListPrice=&squareFeet=&bedrooms=0&bathCount=0&_openHomesOnlyYn=on&_dateRange=on&_virtualTourYn=on"
weight = 2
[[menu.main]]
name = "Search"
parent = "Property Search"
url = "https://blonohouses.idxhome.com/homesearch/137224"
weight = 1
[[menu.main]]
name = "Property Organizer"
parent = "Buyers & Sellers"
url = "https://blonohouses.idxhome.com/organizer/login/137224"
weight = 1
[[menu.main]]
name = "Featured Listings"
url = "https://blonohouses.idxhome.com/featured/137224"
weight = 2
[[menu.main]]
name = "Home"
url = "https://www.blonohouses.com"
weight = 1
[[menu.main]]
name = "Property Search"
weight = 3
[[menu.main]]
name = "Buyers & Sellers"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[taxonomies]
category = "categories"
tag = "tags"
